name: devwhisper

services:
  devwhisper:
    image: devwhisper:latest
    container_name: devwhisper
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
    networks:
      - devwhisper_network
  db:
    image: postgres:16
    container_name: devwhisper_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - devwhisper_vol:/var/lib/postgresql/data
    networks:
      - devwhisper_network

networks:
  devwhisper_network:
    driver: bridge

volumes:
  devwhisper_vol:
